# Generated by Django 5.0.1 on 2024-03-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_media',
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
